name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - "mlruns/**"

  pull_request:
    branches:
      - main

permissions:
  contents: write  # Add this to grant write permissions to the token

env:
  CSV_URL: "MLProject/data/telco_customer_churn_train.csv"
  CSV_TEST_URL: "MLProject/data/telco_customer_churn_test.csv"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow pandas scikit-learn numpy

      - name: Run mlflow project
        run: |
          mlflow run MLProject --env-manager=local

      - name: Install Git LFS
        run: |
          sudo apt-get update
          sudo apt-get install git-lfs -y

      - name: Setup Git LFS
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git lfs install
          git lfs track "mlruns/**"

          git add .gitattributes
          git commit -m "Track mlruns with LFS" || true

      - name: Save mlruns
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add -f mlruns/

          git commit -m "Save mlruns from CI run" || true

          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
